# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afcba71f606f76ce5ea24502ce5f24bc059f7dead1591b248bafbfbc0a2a1ed2e31869f1d5b3227a49897efc6c9c465e24e3217cc4938284ed0f90ee4a6031f1

test:
  secret_key_base: 59e9d1d5e011ae0308c8d27258572dba46add19170bea257083da8720f2550bb7446836e805068dac9e897de1848beff8f5cb0edbec134d820f897326be02e4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
